### ISSUE TITLE
MutableMemoryChunk can't be used with DList.

### ISSUE THREAD

**Issue by Heromyth** [ikod/nbuff#4] opened 2021-07-27 08:26 UTC
It's because that the postblit is disabled. See https://issues.dlang.org/show_bug.cgi?id=22147.

**Comment by ikod** [comment] 2021-07-27 09:37
Hi, @Heromyth 

thanks, will look into it

**Comment by ikod** [comment] 2021-07-27 09:38
@Heromyth 

Do you have some code to reproduce problem?

**Comment by Heromyth** [comment] 2021-07-27 09:40
The full test code:
```d
void main(string[] args) {
    import std.container.dlist;
    DList!B b;
}

struct B
{
    @disable this(this);

    // this(ref return scope inout B rhs) {}  // still not work  
}
```

**Comment by ikod** [comment] 2021-07-27 09:57
@Heromyth 

I see. Pointer to mutable memory can be only consumed or destructed, you can not assign it to another pointer as it is 'Unique'.

Probably I can enable copy constructor, which will behave with move semantic. I don't know if this is desirable.

**Comment by ikod** [comment] 2021-07-27 10:09
@Heromyth 

Btw, why do you need to store mutable buffers in list? They are desined only to be created, filled and converted to immutable buffer.

You can store immutable buffers in Dlist, as they are SharedPtr.

Also struct Nbuff is such list which store Immutable chunks

**Comment by Heromyth** [comment] 2021-07-27 10:14
In our scene, we want to put the MutableMemoryChunk into a queue at first, and consume them slowly.
Maybe we should switch to Nbuff.

**Comment by ikod** [comment] 2021-07-27 10:27
Just for info:  mutable memory chunks intended only for writing, so I assume you place them in the queue for future filling (otherwise, if you queue them for reading then you definitely need immutable chunks or Nbuff).

Ok, so if you place them in queue for future filling - If you need some kind of rate control then you can place in the queue not buffer itself, but just the fact that you will request mutable buffer in the future, and create mutable memory chunks while you consume queue.

Again just for your info - all memory chunks are come from and automatically return to per-thread pool, so taking buffer from pool is quite cheap.

Hope this helps.

**Comment by Heromyth** [comment] 2021-07-27 11:10
We need the queue for cross-thread synchronization.

**Comment by ikod** [comment] 2021-07-27 11:36
I see. Anyway you can't copy or share mutable memory chunk, and this is intentionally, as this make safety warranties for mutable buffer content.

**Comment by ikod** [comment] 2021-07-28 07:14
hi, @Heromyth !

I'm closing it?

**Comment by Heromyth** [comment] 2021-07-28 07:15
That's OK. Thanks.

**Closed as completed** 2021-07-28 07:16 UTC
